### ISSUE TITLE
Missing in Package Control

### ISSUE THREAD

**Issue by pierceray** [seethroughdev/sublime-chai-full-completions#5]
It appears that this package is missing in Package Control.  It has it listed as missing.

https://packagecontrol.io/packages/Chai%20Completions

**Comment by seethroughtrees** [comment]
Thanks for letting me know.  Working on a fix with Package control today.  Will update soon.

**Comment by seethroughdev** [comment]
Looks like it should be back up now.  Try again @pierceray ?

**Comment by pierceray** [comment]
It's available and downloaded in ST3 just fine now.
